name: Build Kernel Rova Pure GCC + KSU-Next

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git ccache automake flex lzop bison \
          build-essential zip curl zlib1g-dev libssl-dev bc \
          python3 libfl-dev mkbootimg \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi g++-arm-linux-gnueabi

      - name: Clone Clean Kernel Source (crDroid rova)
        run: |
          git clone --depth=1 -b 16.0 https://github.com/crdroidandroid/android_kernel_xiaomi_rova kernel-workspace

      - name: Inject KernelSU-Next
        run: |
          cd kernel-workspace
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next

      - name: Compile Kernel
        run: |
          cd kernel-workspace
          
          # Panggil defconfig vendor msm8937
          make O=out ARCH=arm64 vendor/msm8937_defconfig
          
          # Setup defconfig otomatis
          make O=out ARCH=arm64 olddefconfig
          
          # Eksekusi compile pakai GCC bawaan Ubuntu (cross-compiler system)
          make -j$(nproc --all) O=out ARCH=arm64 \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
          KCFLAGS="-w -Wno-error" \
          KCPPFLAGS="-w -Wno-error"

      - name: Upload Hasil Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Rova-GCC-KSUNext
          path: kernel-workspace/out/arch/arm64/boot/Image.gz-dtb
