name: Build Kernel Rova + KSU-Next

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git ccache automake flex lzop bison \
          build-essential zip curl zlib1g-dev libssl-dev bc \
          python3 libfl-dev mkbootimg

      - name: Download Toolchain (Proton-Clang)
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git toolchain

      - name: Clone Kernel Source Rova
        run: |
          git clone --depth=1 -b tr-4.9-rova https://github.com/Thagoo/platform_kernel_xiaomi_msm8917.git kernel-workspace

      - name: Inject KSU-Next
        run: |
          cd kernel-workspace
          # Suntik KSU-Next otomatis
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next

      - name: Compile Kernel
        run: |
          cd kernel-workspace
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH
          
          # Defconfig buat rova, pastiin namanya bener (biasanya rova_defconfig atau msm8937_defconfig)
          make O=out ARCH=arm64 msm8937_defconfig
          
          # Gas build pake Clang
          make -j$(nproc --all) O=out ARCH=arm64 \
          CC=clang \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Upload Hasil Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Rova-KSUNext
          path: kernel-workspace/out/arch/arm64/boot/Image.gz-dtb
